# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='presentacion',
            field=models.FileField(blank=True, null=True, upload_to='presentaciones/'),
        ),
    ]
