# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_auto_20170606_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechtype',
            name='color',
            field=models.CharField(default='#fff', max_length=10),
        ),
    ]
