# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_speechtype_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechtype',
            name='color',
        ),
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(default='#fff', max_length=10),
        ),
    ]
