# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 07:51
from __future__ import unicode_literals

from django.db import migrations
import datetime

def create_default_template(apps, schema_editor):
    BlockSchedule = apps.get_model('proposal', 'BlockSchedule')
    
    # Desayunos
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=7, minute=0),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=8, minute=0),
        is_speech = False,
        text = "Desayuno",
        color = "#eeeeae"     
        )
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=8, minute=0),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=0, minute=45),
        is_speech = False,
        text = "Desayuno",
        color = "#eeeeae"     
        
        )
    
    #Registro
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=8, minute=0),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=9, minute=0),
        is_speech = False,
        text = "Registro",
        color = "#9bafe8"     
        )   
    #Panel de apertura
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=9, minute=0),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=10, minute=30),
        is_speech = False,
        text = "Inauguración 10 a.m. PANEL DE APERTURA",
        color = "#d2695d"     
        )  
    # Traslados
    
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=10, minute=30),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=10, minute=45),
        is_speech = False,
        text = "Traslado",
        color = "#516f6a"     
        )      
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=10, minute=30),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=10, minute=45),
        is_speech = False,
        text = "Traslado",
        color = "#516f6a"     
        )      
 
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=15, minute=0),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=15, minute=15),
        is_speech = False,
        text = "Traslado",
        color = "#516f6a"     
        )             
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=15, minute=0),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=15, minute=15),
        is_speech = False,
        text = "Traslado",
        color = "#516f6a"     
        )        
    
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=16, minute=45),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=17, minute=0),
        is_speech = False,
        text = "Traslado",
        color = "#516f6a"     
        )  
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=16, minute=45),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=17, minute=0),
        is_speech = False,
        text = "Traslado",
        color = "#516f6a"     
        )
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=18, minute=30),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=19, minute=0),
        is_speech = False,
        text = "Traslado",
        color = "#516f6a"     
        ) 
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=18, minute=30),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=19, minute=0),
        is_speech = False,
        text = "Traslado",
        color = "#516f6a"     
        )   
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=8, minute=45),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=9, minute=0),
        is_speech = False,
        text = "Traslado",
        color = "#516f6a"     
        
        )
    
    # Charlas
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=10, minute=45),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=12, minute=15),
        is_speech = True,
        color = "#6cc5af"     
        )     

    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=13, minute=30),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=15, minute=0),
        is_speech = True,
        color = "#6cc5af"     
        )  

    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=15, minute=15),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=16, minute=45),
        is_speech = True,
        color = "#6cc5af"     
        )  

    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=17, minute=0),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=18, minute=30),
        is_speech = True,
        color = "#6cc5af"     
        )  
    
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=9, minute=0),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=10, minute=30),
        is_speech = True,
        color = "#6cc5af"     
        )      

 
 
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=10, minute=45),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=12, minute=15),
        is_speech = True,
        color = "#6cc5af"     
        )     

    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=13, minute=30),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=15, minute=0),
        is_speech = True,
        color = "#6cc5af"     
        )  

    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=15, minute=15),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=16, minute=45),
        is_speech = True,
        color = "#6cc5af"     
        )  

    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=17, minute=0),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=18, minute=30),
        is_speech = True,
        color = "#6cc5af"     
        )  
 
    
    # CENAS

    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=19, minute=0),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=20, minute=0),
        is_speech = False,
        text = "Cena",
        color = "#eeeeae"     
        
        )    
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=19, minute=0),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=20, minute=0),
        is_speech = False,
        text = "Cena",
        color = "#eeeeae"     
        
        )  


    # almuerzos
    
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=21, month=7, year=2017, hour=12, minute=15),
        end_time = datetime.datetime(day=21, month=7, year=2017, hour=1, minute=30),
        is_speech = False,
        text = "Cena",
        color = "#eeeeae"     
        
        )   
    BlockSchedule.objects.create(
        start_time =datetime.datetime(day=22, month=7, year=2017, hour=12, minute=15),
        end_time = datetime.datetime(day=22, month=7, year=2017, hour=1, minute=30),
        is_speech = False,
        text = "Cena",
        color = "#eeeeae"     
        
        )   

class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0009_blockschedule'),
    ]

    operations = [  
      migrations.RunPython(create_default_template),
    ]
