# Generated by Django 3.1.5 on 2021-01-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0011_auto_20170710_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ('pk',), 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
    ]
