# Generated by Django 3.1.5 on 2021-01-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0012_auto_20210105_1102'),
        ('proposal', '0012_auto_20210105_1122'),
    ]

    operations = [
    ]
