# Generated by Django 3.1.5 on 2021-01-10 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0027_auto_20210109_1502'),
        ('proposal', '0013_register_speech_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_speech',
            name='event',
        ),
        migrations.AddField(
            model_name='speech',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl'),
        ),
    ]
