# Generated by Django 3.1.5 on 2021-01-11 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0014_auto_20210109_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='presentacion',
            field=models.FileField(blank=True, null=True, upload_to='presentaciones/', verbose_name='Presentation'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.topic', verbose_name='Topic'),
        ),
    ]
