# Generated by Django 3.1.5 on 2021-01-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0015_auto_20210111_1617'),
        ('proposal', '0015_auto_20210111_1638'),
    ]

    operations = [
    ]
