# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0015_auto_20170706_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='aparecer_en_participantes',
            field=models.BooleanField(default=True),
        ),
    ]
