# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0016_inscription_aparecer_en_participantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='becas',
            options={'verbose_name': 'Beca', 'verbose_name_plural': 'Becas'},
        ),
        migrations.AlterModelOptions(
            name='encuentros_anteriores',
            options={'verbose_name': 'Encuentro anterior', 'verbose_name_plural': 'Encuentros anteriores'},
        ),
        migrations.AlterModelOptions(
            name='gustos',
            options={'verbose_name': 'Gusto', 'verbose_name_plural': 'Gustos'},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='patrocinadores',
            options={'verbose_name': 'Patrocinadores', 'verbose_name_plural': 'Patrocinador'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='paymentoption',
            options={'verbose_name': 'Opción de pago', 'verbose_name_plural': 'Opciones de pago'},
        ),
    ]
