# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0017_auto_20170710_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='direccion_en_su_pais',
            field=models.CharField(blank=True, help_text='Requisito para hospedarse en hotel', max_length=250, null=True, verbose_name='Dirección en su país'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='identification',
            field=models.CharField(help_text='Requisito para hospedarse en hotel', max_length=12, null=True, verbose_name='Identificación en su país/pasaporte'),
        ),
    ]
