# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 23:07
from __future__ import unicode_literals

from django.db import migrations, models


def update_honduras(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Inscripcion = apps.get_model('ecsl', 'Inscription')
    Inscripcion.objects.filter(
        nationality="Hondura").update(nationality="Honduras")


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0020_auto_20170712_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='nationality',
            field=models.CharField(choices=[('Panamá', 'Panamá'), ('Costa Rica', 'Costa Rica'), ('Nicaragua', 'Nicaragua'), ('El Salvador', 'El salvador'), (
                'Guatemala', 'Guatemala'), ('Honduras', 'Honduras'), ('Belize', 'Belize'), ('Otro', 'Otro')], max_length=12, verbose_name='Nacionalidad'),
        ),
        migrations.RunPython(update_honduras),
    ]
