# Generated by Django 3.1.5 on 2021-01-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0023_auto_20210107_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventecsl',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventecsl',
            name='logo',
            field=models.FileField(default='img/logos/RanaCirculo.png', max_length=50, null=True, upload_to='img/logos/'),
        ),
    ]
