# Generated by Django 3.1.5 on 2021-01-10 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0027_auto_20210109_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventecsl',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
