# Generated by Django 3.1.5 on 2021-01-11 06:14

from django.db import migrations


def create_default_data(apps, schema_editor):

    PaymentOption = apps.get_model('ecsl', 'PaymentOption')
    PaymentOption.objects.create(
        name='Paypal',
        identification='Paypal',
        tipo='Paypal',
        email='Paypal@gmail.com'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0030_auto_20210110_2334'),
    ]

    operations = [
        migrations.RunPython(create_default_data),
    ]
