# Generated by Django 3.1.5 on 2021-01-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0035_auto_20210112_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventecsl',
            name='notification_period',
            field=models.BooleanField(default=False, null=True, verbose_name='Notification Period'),
        ),
    ]
