# Generated by Django 3.1.5 on 2021-01-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0035_auto_20210112_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventecsl',
            old_name='oganizer1',
            new_name='organizer1',
        ),
        migrations.RenameField(
            model_name='eventecsl',
            old_name='oganizer2',
            new_name='organizer2',
        ),
    ]
