# Generated by Django 3.1.5 on 2021-01-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0037_auto_20210112_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventecsl',
            name='certificate_Footer',
            field=models.ImageField(blank=True, help_text='Heigth 70px, Width 800px', null=True, upload_to='img/logos/', verbose_name='Certificate Footer Image'),
        ),
        migrations.AlterField(
            model_name='eventecsl',
            name='certificate_Header',
            field=models.ImageField(blank=True, help_text='Heigth 70px, Width 800px', null=True, upload_to='img/logos/', verbose_name='Certificate Header Image'),
        ),
    ]
