# Generated by Django 3.1.5 on 2021-01-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0040_auto_20210112_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventecsl',
            name='proposal_period',
        ),
    ]
