# Generated by Django 3.1.5 on 2021-01-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0042_merge_20210113_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventecsl',
            name='email_event',
            field=models.CharField(max_length=50, null=True, verbose_name='Email Event'),
        ),
    ]
