# Generated by Django 3.1.5 on 2021-01-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0045_eventecsl_email_event'),
        ('ecsl', '0040_auto_20210113_0919'),
    ]

    operations = [
    ]
