version: '3'
volumes:
  rabbitmq-vol:
  db-data:
  db-files:

services:
  rabbitmq:
    image: rabbitmq:3
    container_name: "ecsl_rabbitmq"
    networks:
      - ecslapps
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ecsl
      RABBITMQ_DEFAULT_PASS: ecsl
      RABBITMQ_DEFAULT_VHOST: ecslvhost
    volumes:
      - rabbitmq-vol:/var/lib/rabbitmq

  db:
    image: postgres:latest
    restart: always
    container_name: "db"
    environment:
      POSTGRES_PASSWORD: ecsl
      POSTGRES_USER: ecsl
      POSTGRES_DB: ecsl
    networks:
      - ecslapps
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-files:/files
    ports:
      - 5431:5432

  #registro:
    #image: registroecsl
    #container_name: "ecsl_registro"
    #environment:
      #CELERY_BROKER_URL: "amqp://ecsl:ecsl@rabbitmq:5672/ecslvhost"
      #DB_HOST: db
      #EMAIL_HOST: demoemail
    #networks:
      #- ecslapps
    #ports:
      #- 8080:80

  demoemail:
    image: mailhog/mailhog
    container_name: "demoemail"
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - ecslapps

networks:
  ecslapps:

