# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_auto_20170611_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='presentacion',
            field=models.FileField(blank=True, null=True, upload_to='presentaciones/', verbose_name='Presentación'),
        ),
    ]
