# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0008_auto_20170612_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_speech', models.BooleanField()),
                ('text', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
    ]
