# Generated by Django 3.1.5 on 2021-01-11 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0032_auto_20210111_1617'),
        ('proposal', '0014_auto_20210109_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl', verbose_name='Event'),
        ),
    ]
