# Generated by Django 3.1.5 on 2021-01-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0016_merge_20210111_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Basic speech', max_length=40, verbose_name='Nombre')),
                ('time', models.IntegerField(default=0, verbose_name='Time (in minutes)')),
            ],
            options={
                'verbose_name': 'Duration',
                'verbose_name_plural': 'Duration',
            },
        ),
    ]
