# Generated by Django 3.1.5 on 2021-01-21 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0017_specialactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialactivity',
            options={'verbose_name': 'Actividad Especial', 'verbose_name_plural': 'Actividades Especiales'},
        ),
    ]
