# Generated by Django 3.1.5 on 2021-01-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0018_auto_20210120_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='time_given',
            field=models.ForeignKey(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_asked', to='proposal.speechtime', verbose_name='Duration'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_given', to='proposal.speechtime', verbose_name='Duration Assigned'),
        ),
    ]
