# Generated by Django 3.1.5 on 2021-01-21 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0047_auto_20210115_1536'),
        ('proposal', '0021_merge_20210120_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialactivity',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='specialactivity',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='specialactivity',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.room', verbose_name='Room'),
        ),
    ]
