# Generated by Django 3.1.5 on 2021-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0022_auto_20210120_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialactivity',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='is Scheduled'),
        ),
        migrations.AddField(
            model_name='speech',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='is Scheduled'),
        ),
        migrations.AlterField(
            model_name='specialactivity',
            name='end_time',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='specialactivity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='specialactivity',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
    ]
