# Generated by Django 3.1.5 on 2021-01-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0023_merge_20210121_1122'),
        ('proposal', '0023_auto_20210121_0836'),
        ('proposal', '0023_merge_20210121_1120'),
    ]

    operations = [
    ]
