# Generated by Django 3.2.12 on 2022-03-01 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0031_speech_speech_time_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechschedule',
            name='html_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
