# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0005_auto_20170604_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='camiseta',
            field=models.CharField(choices=[('S', 'S'), ('XS', 'XS'), ('M', 'M'), ('XM', 'XM'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscription',
            name='born_date',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='encuentros',
            field=models.ManyToManyField(blank=True, help_text='Use ctrl o command en mac para seleccionar más de uno', to='ecsl.Encuentros_Anteriores', verbose_name='Encuentros anteriores en los que ha participado'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='gustos_manias',
            field=models.ManyToManyField(help_text='Use ctrl o command en mac para seleccionar más de uno', to='ecsl.Gustos', verbose_name='Por favor seleccione las opciones que correspondan a sus gustos, usos, costumbres, manías'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='other_nationality',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Si marcó otro indique el país de procedencia'),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='identification',
            field=models.CharField(max_length=30, null=True, verbose_name='Identificación'),
        ),
    ]
