# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0012_auto_20170618_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='hora_de_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='hora_de_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
