# Generated by Django 3.1.5 on 2021-01-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0021_auto_20170712_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventECSL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(null=True, verbose_name='Fecha finalización')),
                ('location', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True, verbose_name='Descripción')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='becas',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl'),
        ),
        migrations.AddField(
            model_name='patrocinadores',
            name='event',
            field=models.ManyToManyField(to='ecsl.EventECSL'),
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl'),
        ),
    ]
