# Generated by Django 3.1.5 on 2021-01-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0032_auto_20210111_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventecsl',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
