# Generated by Django 3.1.5 on 2021-01-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0035_auto_20210112_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventecsl',
            name='beca_end',
            field=models.DateField(null=True, verbose_name='Scholarship application end period'),
        ),
        migrations.AlterField(
            model_name='eventecsl',
            name='beca_start',
            field=models.DateField(null=True, verbose_name='Scholarship application start period'),
        ),
    ]
