# Generated by Django 3.1.5 on 2021-01-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0036_eventecsl_notification_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventecsl',
            name='notification_period',
        ),
    ]
