# Generated by Django 3.1.5 on 2021-01-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0037_remove_eventecsl_notification_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventecsl',
            name='phone_event',
            field=models.CharField(max_length=15, null=True, verbose_name='Phone'),
        ),
    ]
