# Generated by Django 3.1.5 on 2021-01-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0036_auto_20210112_1557'),
        ('ecsl', '0038_auto_20210112_1528'),
    ]

    operations = [
    ]
