# Generated by Django 3.1.5 on 2021-01-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0039_auto_20210112_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventecsl',
            name='end_date_proposal',
            field=models.DateField(null=True, verbose_name='End Date Proposal'),
        ),
        migrations.AddField(
            model_name='eventecsl',
            name='start_date_proposal',
            field=models.DateField(null=True, verbose_name='Start Date Proposal'),
        ),
    ]
