# Generated by Django 3.1.5 on 2021-01-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0039_merge_20210113_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventecsl',
            name='max_inscription',
            field=models.IntegerField(default=250, null=True, verbose_name='Maximum Inscriptions'),
        ),
        migrations.AlterField(
            model_name='eventecsl',
            name='certificate_Footer',
            field=models.ImageField(blank=True, help_text='Height 70px, Width 800px', null=True, upload_to='img/logos/', verbose_name='Certificate Footer Image'),
        ),
        migrations.AlterField(
            model_name='eventecsl',
            name='certificate_Header',
            field=models.ImageField(blank=True, help_text='Height 70px, Width 800px', null=True, upload_to='img/logos/', verbose_name='Certificate Header Image'),
        ),
    ]
