# Generated by Django 3.1.5 on 2021-01-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0041_remove_eventecsl_proposal_period'),
        ('ecsl', '0038_auto_20210112_1528'),
    ]

    operations = [
    ]
