# Generated by Django 3.1.5 on 2021-01-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0043_eventecsl_email_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventecsl',
            name='email_event',
        ),
    ]
