# Generated by Django 3.1.5 on 2021-01-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0047_auto_20210115_1753'),
        ('ecsl', '0047_auto_20210115_1536'),
    ]

    operations = [
    ]
