# Generated by Django 3.1.5 on 2021-01-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0049_auto_20210118_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl', verbose_name='Event'),
        ),
    ]
