# Generated by Django 3.1.5 on 2021-02-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0050_auto_20210126_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='alimentary_restriction',
            field=models.TextField(blank=True, null=True, verbose_name='¿Tiene alguna necesidad específica de alimentación y hospedaje o alguna condición de salud especial?'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='comentario_general',
            field=models.TextField(blank=True, null=True, verbose_name='Si tiene algún comentario y/o si quiere colaborar con la organización del ECSL por favor comente en este espacio.'),
        ),
    ]
