# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_speech_presentacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ('pk',), 'permissions': (('view_speech', 'Can see available Speech'),)},
        ),
    ]
