# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_auto_20170612_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Topic', verbose_name='Eje temático'),
        ),
    ]
