# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0010_cargaBloques'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockschedule',
            options={'verbose_name': 'Bloque de horario', 'verbose_name_plural': 'Bloques de horarios'},
        ),
        migrations.AlterModelOptions(
            name='register_speech',
            options={'verbose_name': 'Registro en actividad', 'verbose_name_plural': 'Registros en actividades'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ('pk',), 'permissions': (('view_speech', 'Can see available Speech'),), 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='speechschedule',
            options={'verbose_name': 'Horario de actividad', 'verbose_name_plural': 'Horarios de actividades'},
        ),
        migrations.AlterModelOptions(
            name='speechtype',
            options={'verbose_name': 'Tipo de actividad', 'verbose_name_plural': 'Tipos de actividad'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Temática', 'verbose_name_plural': 'Temáticas'},
        ),
        migrations.AddField(
            model_name='room',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='mapa'),
        ),
    ]
