# Generated by Django 3.1.5 on 2021-01-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0022_auto_20210107_1336'),
        ('proposal', '0012_auto_20210105_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_speech',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl'),
        ),
    ]
