# Generated by Django 3.1.5 on 2021-01-20 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0047_auto_20210115_1536'),
        ('proposal', '0016_merge_20210111_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl', verbose_name='Event'),
        ),
    ]
