# Generated by Django 3.1.5 on 2021-01-21 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0018_auto_20210120_1807'),
        ('proposal', '0020_auto_20210120_1745'),
    ]

    operations = [
    ]
