# Generated by Django 3.1.5 on 2021-01-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0022_auto_20210120_2157'),
        ('proposal', '0017_room_event'),
    ]

    operations = [
    ]
