# Generated by Django 3.1.5 on 2021-01-21 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0024_merge_20210121_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechschedule',
            name='special',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.specialactivity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='mapa', verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='room',
            name='spaces',
            field=models.SmallIntegerField(default=30, verbose_name='Spaces'),
        ),
        migrations.AlterField(
            model_name='specialactivity',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='proposal.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='specialactivity',
            name='start_time',
            field=models.DateTimeField(default='', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='speechschedule',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='proposal.room'),
        ),
        migrations.AlterField(
            model_name='speechschedule',
            name='speech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.speech'),
        ),
        migrations.AlterField(
            model_name='speechtime',
            name='name',
            field=models.CharField(default='Basic speech', max_length=40, verbose_name='Name'),
        ),
    ]
