# Generated by Django 3.1.5 on 2021-01-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0047_auto_20210115_1536'),
        ('proposal', '0027_blockschedule_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialactivity',
            name='time',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='time_asked',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='time_given',
        ),
        migrations.AddField(
            model_name='specialactivity',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.speechtype', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='speechtype',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='speechtype',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Is Special Activity'),
        ),
        migrations.AddField(
            model_name='speechtype',
            name='time',
            field=models.IntegerField(default=10, verbose_name='Duration (in minutes)'),
        ),
        migrations.AlterField(
            model_name='blockschedule',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='specialactivity',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='speechschedule',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.room'),
        ),
        migrations.DeleteModel(
            name='SpeechTime',
        ),
    ]
