# Generated by Django 3.1.5 on 2021-01-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0050_auto_20210126_1037'),
        ('proposal', '0027_blockschedule_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecsl.eventecsl', verbose_name='Event'),
        ),
    ]
