# Generated by Django 3.1.5 on 2021-01-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0028_auto_20210126_1037'),
        ('proposal', '0028_auto_20210126_1117'),
    ]

    operations = [
    ]
