# Generated by Django 3.1.5 on 2021-02-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0030_auto_20210211_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='speech_time_asked',
            field=models.IntegerField(default=0, verbose_name='Time Asked'),
        ),
    ]
