# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecsl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='email',
            field=models.EmailField(default='not-reply@ecsl2017.softwarelibre.ca', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscription',
            name='alimentary_restriction',
            field=models.TextField(blank=True, null=True, verbose_name='¿Tiene alguna necesidad específica de alimentación y hospedaje o alguna condición de salud especial?.'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='comentario_general',
            field=models.TextField(blank=True, null=True, verbose_name='Si tiene algún comentario y/o si quiere colaborar con la organización del 9° ECSL por favor comente en este espacio.'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='gustos_manias',
            field=models.ManyToManyField(help_text='Use ctrl o command en mac para seleccionar más de uno', to='ecsl.Gustos'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='health_consideration',
            field=models.TextField(blank=True, null=True, verbose_name='Condiciones de Salud'),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='tipo',
            field=models.CharField(max_length=255, verbose_name='Opción de envío'),
        ),
    ]
