# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0002_auto_20170602_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paquete',
            field=models.CharField(choices=[('Completo', 'Completo'), ('Sin hotel', 'Sin hotel')], default='Completo', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsl.PaymentOption', verbose_name='Opción de pago'),
        ),
    ]
