# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0004_auto_20170602_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuentros_Anteriores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='encuentros',
            field=models.ManyToManyField(to='ecsl.Encuentros_Anteriores'),
        ),
    ]
