# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 17:30
from __future__ import unicode_literals

from django.db import migrations


def create_default_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Encuentros_Anteriores = apps.get_model('ecsl', 'Encuentros_Anteriores')

    for x in ['No he participado antes', '2009 Nicaragua', '2010 Costa Rica', '2011 El Salvador', 
                  '2012 Guatemala', '2013 Belize', '2014 Panamá', 
                  '2015 Honduras', '2016 Nicaragua']:
        
        Encuentros_Anteriores.objects.create(name=x)
    
    Gustos = apps.get_model('ecsl', 'Gustos')
    
    for x in ['Ronco',
                'Me gusta irme de fiesta',
                'Me gusta dormir temprano',
                'Puedo levantarme temprano sin problema', 'Como mucho']:

        Gustos.objects.create(name=x)
        
    PaymentOption= apps.get_model('ecsl', 'PaymentOption')
    PaymentOption.objects.create(
        name = 'Dialogía de Información y Comunicación SC',
        identification = 'CR38015109620020034632',
        tipo = 'Depósito bancario',
        email = 'cfloreshine@gmail.com' 
    )
    PaymentOption.objects.create(
        name = 'Luis Enrique Zárate Montero',
        identification = '402120119',
        tipo = 'MoneyGram',
        email = 'luisza14@gmail.com' 
    )
  
    PaymentOption.objects.create(
        name = 'José Daniel Jenkins Pérez',
        identification = '112470493',
        tipo = 'MoneyGram',
        email = 'jeukel@gmail.com' 
    )  

    PaymentOption.objects.create(
        name = 'Leonardo Jiménez Quijano',
        identification = '110140191',
        tipo = 'MoneyGram',
        email = 'leojimenezcr@gmail.com' 
    )    

    PaymentOption.objects.create(
        name = 'Diego Gonzalo Chacón Rojas',
        identification = '205590806',
        tipo = 'Western Union',
        email = 'diego.chacon@gmail.com' 
    )      

    PaymentOption.objects.create(
        name = 'Diego Gonzalo Chacón Rojas',
        identification = '205590806',
        tipo = 'MoneyGram',
        email = 'diego.chacon@gmail.com' 
    ) 
   


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0006_auto_20170604_1811'),
    ]

    operations = [
         migrations.RunPython(create_default_data),
    ]

