# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0007_load_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='observacion_gustos_manias',
            field=models.TextField(blank=True, null=True, verbose_name='Alguna otra observación sobre sus gustos, usos, costumbres y manías.'),
        ),
    ]
