# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0009_becas'),
    ]

    operations = [
        migrations.AddField(
            model_name='becas',
            name='estado',
            field=models.SmallIntegerField(choices=[(0, 'Solicitada'), (1, 'Aprobada'), (2, 'Rechazada')], default=0),
        ),
    ]
