# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0010_becas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='nationality',
            field=models.CharField(choices=[('Panamá', 'Panamá'), ('Costa Rica', 'Costa Rica'), ('Nicaragua', 'Nicaragua'), ('El Salvador', 'El salvador'), ('Guatemala', 'Guatemala'), ('Hondura', 'Honduras'), ('Belize', 'Belize'), ('Otro', 'Otro')], max_length=12, verbose_name='Nacionalidad'),
        ),
    ]
