# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0011_auto_20170612_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='codigo_de_referencia',
            field=models.CharField(help_text='Identificación de transacción o código de referencia', max_length=40, verbose_name='Id de transacción'),
        ),
    ]
