# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0013_auto_20170706_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='lugar_de_arribo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='medio_de_transporte',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='observaciones_del_viaje',
            field=models.TextField(blank=True, help_text='Si viaja en avión agregue el número de vuelo.', null=True),
        ),
    ]
