# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0014_auto_20170706_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='hora_de_llegada',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='hora_de_salida',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
