# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0018_auto_20170711_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='identification',
            field=models.CharField(help_text='Requisito para hospedarse en hotel', max_length=30, null=True, verbose_name='Identificación en su país/pasaporte'),
        ),
    ]
