# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0019_auto_20170711_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='identification',
            field=models.CharField(help_text='Requisito para hospedarse en hotel', max_length=50, null=True, verbose_name='Identificación en su país/pasaporte'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='institution',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Institución'),
        ),
    ]
