# Generated by Django 3.1.5 on 2021-01-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0022_auto_20210107_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventecsl',
            old_name='status',
            new_name='current',
        ),
    ]
