# Generated by Django 3.1.5 on 2021-01-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0026_auto_20210107_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventecsl',
            name='logo',
            field=models.ImageField(null=True, upload_to='img/logos/', verbose_name='Logo'),
        ),
    ]
