# Generated by Django 3.1.5 on 2021-01-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0029_auto_20210110_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Paquete', 'verbose_name_plural': 'Paquetes'},
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecsl.package', verbose_name='Paquete'),
        ),
    ]
