# Generated by Django 3.1.5 on 2021-01-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsl', '0032_auto_20210111_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventecsl',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Current'),
        ),
        migrations.AlterField(
            model_name='eventecsl',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventecsl',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='eventecsl',
            name='location',
            field=models.CharField(max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='eventecsl',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
    ]
