#!/bin/bash

NAME="beat_ecsl"                                  # Name of the application
DJANGODIR=/ecsl            # Django project directory
DJANGO_SETTINGS_MODULE=ecsl_proj.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=ecsl_proj.wsgi                     # WSGI module name

exec  celery -A ecsl_proj beat  --schedule django_celery_beat.schedulers:DatabaseScheduler --loglevel=INFO --pidfile="/run/bead_`date  +"%Y%m%d%H%M%S"`.pid"
