#!/bin/bash
 
NAME="ecslCelery" # Name of the application 
DJANGODIR=/ecsl # Django project directory 
NUM_WORKERS=2 # how many worker processes should Gunicorn spawn 
DJANGO_SETTINGS_MODULE=ECSL.settings # which settings file should Django use 
DJANGO_WSGI_MODULE=ECSL.wsgi  # WSGI module name 

cd $DJANGODIR 

exec celery -A ECSL worker  -l INFO  -c $NUM_WORKERS --pidfile="/run/worker_`date  +"%Y%m%d%H%M%S"`.pid"

